[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"  # Specify the Solidity version
fs_permissions = [
    { access = "read-write", path = "./logs"},
    { access = "read", path = "./.env" },
    { access = "read-write", path = "./logs/reserves.json" }
]
ffi = true
verbosity = 3

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options